#!/bin/bash
set -e

###############################################################################
# Artio Mine Bot — Docker VM Deployment Script
# Usage: ./deploy.sh <openai-api-key> [host] [port]
# Example: ./deploy.sh sk-proj-xxx craig@dockerdev 8000
###############################################################################

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
OPENAI_API_KEY="${1:-}"
SSH_HOST="${2:-craig@dockerdev}"
PORT="${3:-8000}"
FRONTEND_PORT="5173"
REPO_URL="https://github.com/bighog300/artio-mine-bot.git"
REMOTE_PATH="/home/craig/artio-mine-bot"

###############################################################################
# Validation
###############################################################################

if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${RED}❌ Error: OpenAI API key required${NC}"
    echo "Usage: $0 <openai-api-key> [ssh-host] [port]"
    echo "Example: $0 sk-proj-abc123 craig@dockerdev 8000"
    exit 1
fi

if [ -z "$SSH_HOST" ]; then
    SSH_HOST="craig@dockerdev"
    echo -e "${YELLOW}ℹ️  Using default SSH host: $SSH_HOST${NC}"
fi

# Test SSH connectivity
if ! ssh -q -o BatchMode=yes "$SSH_HOST" "echo connected" 2>/dev/null; then
    echo -e "${RED}❌ Cannot connect to $SSH_HOST via SSH${NC}"
    echo "Please ensure:"
    echo "  1. SSH key is configured (ssh-keygen)"
    echo "  2. SSH key is added to remote host"
    echo "  3. Host is reachable"
    exit 1
fi

echo -e "${GREEN}✅ SSH connectivity verified${NC}"

###############################################################################
# Deployment Steps
###############################################################################

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Deploying Artio Mine Bot to $SSH_HOST${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Step 1: Prepare remote directory
echo -e "${BLUE}[1/6]${NC} Preparing remote directory..."
ssh "$SSH_HOST" << 'REMOTE_SCRIPT'
#!/bin/bash
set -e

REMOTE_PATH="/home/craig/artio-mine-bot"

# Create directory structure
mkdir -p "$REMOTE_PATH"
cd "$REMOTE_PATH"

# Check if already cloned
if [ -d ".git" ]; then
    echo "  Pulling latest changes..."
    git pull origin main
else
    echo "  Cloning repository..."
    git clone https://github.com/bighog300/artio-mine-bot.git . 2>/dev/null || \
    git clone https://github.com/bighog300/artio-mine-bot.git .
fi

echo "✅ Repository ready at $REMOTE_PATH"
REMOTE_SCRIPT

echo -e "${GREEN}✅ Remote directory prepared${NC}"

# Step 2: Create .env file
echo -e "${BLUE}[2/6]${NC} Creating .env configuration..."

ssh "$SSH_HOST" << REMOTE_SCRIPT
#!/bin/bash
set -e

REMOTE_PATH="/home/craig/artio-mine-bot"
cd "\$REMOTE_PATH"

# Backup existing .env if present
if [ -f ".env" ]; then
    cp .env .env.backup.\$(date +%s)
    echo "  Backed up existing .env"
fi

# Create new .env file
cat > .env << 'ENV_FILE'
# Artio Miner Configuration
# Generated by deployment script

# Required — AI feature
OPENAI_API_KEY=${OPENAI_API_KEY}
OPENAI_MODEL=gpt-4o

# Database — SQLite (persistent in volume)
DATABASE_URL=sqlite+aiosqlite:////app/data/miner.db

# Optional — Artio platform export
# ARTIO_API_URL=https://your-artio-instance.vercel.app
# ARTIO_API_KEY=your-artio-api-key

# Crawl settings
MAX_CRAWL_DEPTH=3
MAX_PAGES_PER_SOURCE=500
CRAWL_DELAY_MS=1000

# Browser automation
PLAYWRIGHT_ENABLED=true

# Frontend CORS
CORS_ORIGINS=http://localhost:${PORT}

# Server
ENVIRONMENT=production
ENV_FILE

echo "✅ .env created with API key configured"
REMOTE_SCRIPT

echo -e "${GREEN}✅ Configuration file created${NC}"

# Step 3: Check Docker installation
echo -e "${BLUE}[3/6]${NC} Verifying Docker installation..."

ssh "$SSH_HOST" << 'REMOTE_SCRIPT'
#!/bin/bash

# Check Docker
if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Install with:"
    echo "   curl -fsSL https://get.docker.com | sh"
    exit 1
fi

# Check Docker Compose
if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose not found. Install with:"
    echo "   pip install docker-compose"
    exit 1
fi

docker --version
docker-compose --version

echo "✅ Docker tooling verified"
REMOTE_SCRIPT

echo -e "${GREEN}✅ Docker verified${NC}"

# Step 4: Build and start containers
echo -e "${BLUE}[4/6]${NC} Building Docker images..."
echo "  This may take 3-5 minutes on first build (Playwright installation)..."

ssh "$SSH_HOST" << REMOTE_SCRIPT
#!/bin/bash
set -e

cd /home/craig/artio-mine-bot

# Stop existing containers
echo "  Stopping existing containers..."
docker-compose down 2>/dev/null || true

# Build new images
echo "  Building backend image..."
docker-compose build --no-cache api

echo "  Building frontend image..."
docker-compose build --no-cache frontend

echo "✅ Docker images built successfully"
REMOTE_SCRIPT

echo -e "${GREEN}✅ Docker images built${NC}"

# Step 5: Start containers
echo -e "${BLUE}[5/6]${NC} Starting containers..."

ssh "$SSH_HOST" << REMOTE_SCRIPT
#!/bin/bash
set -e

cd /home/craig/artio-mine-bot

# Start containers in background
docker-compose up -d

# Wait for services to be ready
echo "  Waiting for services to start..."
sleep 5

# Check API health
MAX_RETRIES=10
RETRY=0
while [ \$RETRY -lt \$MAX_RETRIES ]; do
    if curl -s http://localhost:8000/health > /dev/null 2>&1; then
        echo "✅ API is healthy"
        break
    fi
    RETRY=\$((RETRY + 1))
    echo "  Attempt \$RETRY/\$MAX_RETRIES: Waiting for API to start..."
    sleep 3
done

if [ \$RETRY -eq \$MAX_RETRIES ]; then
    echo "⚠️  API startup timeout. Check logs with: docker-compose logs api"
    exit 1
fi

# Show container status
docker-compose ps

echo "✅ Containers started successfully"
REMOTE_SCRIPT

echo -e "${GREEN}✅ Containers started${NC}"

# Step 6: Health check
echo -e "${BLUE}[6/6]${NC} Running health checks..."

ssh "$SSH_HOST" << 'REMOTE_SCRIPT'
#!/bin/bash

cd /home/craig/artio-mine-bot

echo "  Testing API health..."
API_HEALTH=$(curl -s http://localhost:8000/health | grep -o '"status":"ok"' || echo "")
if [ -n "$API_HEALTH" ]; then
    echo "  ✅ API responding"
else
    echo "  ⚠️  API not responding"
    docker-compose logs api | tail -20
fi

echo "  Testing database connectivity..."
DB_STATUS=$(curl -s http://localhost:8000/health | grep -o '"db":"ok"' || echo "")
if [ -n "$DB_STATUS" ]; then
    echo "  ✅ Database initialized"
else
    echo "  ⚠️  Database not ready"
fi

echo ""
echo "Service Status:"
docker-compose ps

REMOTE_SCRIPT

echo -e "${GREEN}✅ Health checks complete${NC}"

###############################################################################
# Deployment Summary
###############################################################################

echo ""
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ DEPLOYMENT SUCCESSFUL${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}Access your application:${NC}"
echo ""
echo -e "  🌐 ${YELLOW}Frontend:${NC} http://$SSH_HOST:$FRONTEND_PORT"
echo -e "  🔌 ${YELLOW}API:${NC} http://$SSH_HOST:8000"
echo -e "  💚 ${YELLOW}Health:${NC} http://$SSH_HOST:8000/health"
echo ""
echo -e "${BLUE}Useful commands:${NC}"
echo ""
echo -e "  View logs:        ${YELLOW}ssh $SSH_HOST 'cd artio-mine-bot && docker-compose logs -f'${NC}"
echo -e "  Stop services:    ${YELLOW}ssh $SSH_HOST 'cd artio-mine-bot && docker-compose down'${NC}"
echo -e "  Restart services: ${YELLOW}ssh $SSH_HOST 'cd artio-mine-bot && docker-compose restart'${NC}"
echo -e "  Access shell:     ${YELLOW}ssh $SSH_HOST 'cd artio-mine-bot && docker-compose exec api /bin/bash'${NC}"
echo -e "  Check DB:         ${YELLOW}ssh $SSH_HOST 'docker-compose exec api sqlite3 /app/data/miner.db \".tables\"'${NC}"
echo ""
echo -e "${BLUE}Configuration:${NC}"
echo ""
echo -e "  Repository:  /home/craig/artio-mine-bot"
echo -e "  Config file: /home/craig/artio-mine-bot/.env"
echo -e "  Data volume: Docker named volume 'artio_data'"
echo ""
echo -e "${YELLOW}Note:${NC} First-time build takes 3-5 minutes due to Playwright browser installation."
echo "      Subsequent deployments will be much faster with Docker layer caching."
echo ""
