"""initial schema

Revision ID: 5e2c81fd2cc6
Revises: 
Create Date: 2026-04-12 20:11:38.015897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2c81fd2cc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('site_map', sa.Text(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('page_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('fetch_method', sa.String(), nullable=True),
    sa.Column('html_truncated', sa.Boolean(), nullable=False),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'url')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index('ix_pages_page_type', ['page_type'], unique=False)
        batch_op.create_index('ix_pages_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_pages_status', ['status'], unique=False)

    op.create_table('records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('venue_name', sa.String(), nullable=True),
    sa.Column('venue_address', sa.String(), nullable=True),
    sa.Column('artist_names', sa.Text(), nullable=False),
    sa.Column('ticket_url', sa.String(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('price_text', sa.String(), nullable=True),
    sa.Column('curator', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('mediums', sa.Text(), nullable=False),
    sa.Column('collections', sa.Text(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('raw_error', sa.Text(), nullable=True),
    sa.Column('extraction_model', sa.String(), nullable=True),
    sa.Column('extraction_provider', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('confidence_band', sa.String(), nullable=False),
    sa.Column('confidence_reasons', sa.Text(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('primary_image_id', sa.String(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index('ix_records_confidence_band', ['confidence_band'], unique=False)
        batch_op.create_index('ix_records_record_type', ['record_type'], unique=False)
        batch_op.create_index('ix_records_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_records_status', ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_jobs_status', ['status'], unique=False)

    op.create_table('images',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=True),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['records.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_id', 'url')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index('ix_images_record_id', ['record_id'], unique=False)
        batch_op.create_index('ix_images_source_id', ['source_id'], unique=False)

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_records_primary_image_id_images",
            "images",
            ["primary_image_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_records_primary_image_id_images', type_='foreignkey')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('ix_images_source_id')
        batch_op.drop_index('ix_images_record_id')

    op.drop_table('images')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index('ix_pages_status')
        batch_op.drop_index('ix_pages_source_id')
        batch_op.drop_index('ix_pages_page_type')

    op.drop_table('pages')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')
        batch_op.drop_index('ix_jobs_source_id')

    op.drop_table('jobs')
    op.drop_table('sources')
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index('ix_records_status')
        batch_op.drop_index('ix_records_source_id')
        batch_op.drop_index('ix_records_record_type')
        batch_op.drop_index('ix_records_confidence_band')

    op.drop_table('records')
    # ### end Alembic commands ###
